services:

  hackathon-flask-app:
    container_name: hackathon-flask-app
    build:
      context: .
      dockerfile: ./docker/flask/Dockerfile
    ports:
      - 5010:5010
    volumes:
      - ./app-flask:/app
      - ./files/work/train_dataset:/app/train_dataset
    environment:
      - FLASK_APP=app.py
    networks:
      - hackathon-net

  hackathon-mongo:
    container_name: hackathon-mongo
    image: mongodb/mongodb-atlas-local
    ports:
      - 37017:27017
    volumes:
      - hackathon-mongodb:/data/db
      # - ./config:/data/configdb
    environment:
      MONGODB_INITDB_ROOT_USERNAME: user
      MONGODB_INITDB_ROOT_PASSWORD: pass
    networks:
      - hackathon-net


  hackathon-jupyter:
    container_name: hackathon-jupyter
    build: 
      context: .
      dockerfile: ./docker/jupyter/Dockerfile
    volumes:
      - ./files/work:/home/jovyan
      - ~/Documents:/home/jovyan/Documents
      - ~/Downloads:/home/jovyan/Downloads
    ports:
      - 8899:8888
      - 8890:5001
    depends_on:
      - hackathon-mongo
      - hackathon-flask-app
    networks:
      - hackathon-net
    command: "start-notebook.sh --NotebookApp.token="

volumes:
  hackathon-mongodb:
    driver: local

networks:
  hackathon-net:
    driver: bridge
