services:

  hackathon-flask-app:
    container_name: hackathon-flask-app
    build:
      context: .
      dockerfile: ./docker/flask/Dockerfile
    ports:
      - 5010:5010
    volumes:
      - ./app-flask:/app
      - ./files/work/train_dataset:/app/static/train_dataset
    environment:
      - FLASK_APP=app.py
    networks:
      - hackathon-net

  hackathon-mongo:
    container_name: hackathon-mongo
    image: mongodb/mongodb-atlas-local
    ports:
      - 37017:27017
    volumes:
      - hackathon-mongodb:/data/db
      - hackathon-mongot:/data/mongot
      # - ./config:/data/configdb
    environment:
      MONGODB_INITDB_ROOT_USERNAME: user
      MONGODB_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: PassW0rd
      # Comment out or remove keyfile-related config unless you intend to use it
      # MONGO_INITDB_KEYFILE: /data/configdb/keyfile
    networks:
      - hackathon-net


  hackathon-jupyter:
    container_name: hackathon-jupyter
    build: 
      context: .
      dockerfile: ./docker/jupyter/Dockerfile
    volumes:
      - ./files/work:/home/jovyan
      - ~/Documents:/home/jovyan/Documents
      - ~/Downloads:/home/jovyan/Downloads
    ports:
      - 8899:8888
      - 8890:5001
    depends_on:
      - hackathon-mongo
      - hackathon-flask-app
    networks:
      - hackathon-net
    command: "start-notebook.sh --NotebookApp.token="

volumes:
  hackathon-mongodb:
  hackathon-mongot:

networks:
  hackathon-net:
    driver: bridge
